### ISSUE TITLE
Implement basic SMTPClient

### ISSUE THREAD

**Issue by srg-kostyrko** [metarhia/metamail#4]
As base for all the other SMTP related functionality we need to implement SMTPClient that will be responsible for communication with SMTP server. 

Latest [RFC 5321](https://datatracker.ietf.org/doc/html/rfc5321) should be used for SMTP protocol description. Also [RFC 4952](https://datatracker.ietf.org/doc/html/rfc4954) describes authentication flow.

Following capabilities should be implemented:

- [ ] Establishing connection
- [ ] Using secure connection
- [ ] Sending commands and parsing responses
- [ ] Sending data stream
- [ ] SMTP handshake
- [ ] Basic auth

You can use [Ethereal](https://ethereal.email/create) for SMTP server data and credentials.

**Comment by srg-kostyrko** [comment]
I have started working on this task

**Comment by tshemsedinov** [comment]
See alternative implementation here: https://www.npmjs.com/package/nodemailer
